name: Achievements
on: [push, workflow_dispatch]
jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Achievement Action
        run: echo 'ğŸ† GitHub Achievements Unlocked!'
